# Ukrainian translation dictionary to decode Andrulko edition
# https://kuli.com.ua/grand-theft-auto-vice-city#translations

[decode_table]

# LATIN
75  = 'К' # 'K'
84  = 'Т' # 'T'
89  = 'T' # 'Y'
107 = 'к' # 'k'
116 = 'т' # 't'
121 = 't' # 'y'

# À-Ï, Ò-Ö, Ú-Ü, Ñ-¿

128 = 'Б' # 'À'
129 = 'В' # 'Á'
130 = 'Г' # 'Â'
131 = 'Д' # 'Ä'
132 = 'Ж' # 'Æ'
133 = 'З' # 'Ç'
134 = 'И' # 'È'
135 = 'Й' # 'É'
136 = 'Л' # 'Ê'
137 = 'М' # 'Ë'
138 = 'Н' # 'Ì'
139 = 'П' # 'Í'
140 = 'У' # 'Î'
141 = 'Ф' # 'Ï'
142 = 'Ц' # 'Ò'
143 = 'Ч' # 'Ó'
144 = 'Ш' # 'Ô'
145 = 'Щ' # 'Ö'
147 = 'Ь' # 'Ú'
148 = 'Є' # 'Û'
149 = 'Ю' # 'Ü'
173 = 'Я' # 'Ñ'

# à-ï, ò-ó, ô-ö, ú-ü, ñ

151 = 'б' # 'à'
152 = 'в' # 'á'
153 = 'г' # 'â'
154 = 'д' # 'ä'
155 = 'ж' # 'æ'
156 = 'з' # 'ç'
157 = 'и' # 'è'
158 = 'й' # 'é'
159 = 'л' # 'ê'
160 = 'м' # 'ë'
161 = 'н' # 'ì'
162 = 'п' # 'í'
163 = 'у' # 'î'
164 = 'ф' # 'ï'
165 = 'ц' # 'ò'
166 = 'ч' # 'ó'
167 = 'ш' # 'ô'
168 = 'щ' # 'ö'
170 = 'ь' # 'ú'
171 = 'є' # 'û'
172 = 'ю' # 'ü'
174 = 'я' # 'ñ'
175 = 'ї' # '¿'